// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace google_sheet_api_service.Migrations.MvcEnvironmentMusic
{
    [DbContext(typeof(MvcEnvironmentMusicContext))]
    [Migration("20220107092756_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("google_sheet_api_service.Models.EnvironmentMusic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("fadeInOutDuration")
                        .HasColumnType("REAL");

                    b.Property<string>("fadeInOutEase")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("fadeLoopDelay")
                        .HasColumnType("REAL");

                    b.Property<double>("fadeOutDelay")
                        .HasColumnType("REAL");

                    b.Property<bool>("isFadeLoop")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("isLoop")
                        .HasColumnType("INTEGER");

                    b.Property<int>("islandGid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("islandName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("music")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("startDelay")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("EnvironmentMusic");
                });
#pragma warning restore 612, 618
        }
    }
}
