// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace google_sheet_api_service.Migrations.MvcStoryDialogue
{
    [DbContext(typeof(MvcStoryDialogueContext))]
    [Migration("20220103083500_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("google_sheet_api_service.Models.StoryDialogue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("characterName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("contentKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("dialogueSortIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("optionDialogue01")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("optionDialogue01Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("optionDialogue02")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("optionDialogue02Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("storyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("stroyGid")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("StoryDialogue");
                });
#pragma warning restore 612, 618
        }
    }
}
