// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace google_sheet_api_service.Migrations.MvcStory
{
    [DbContext(typeof(MvcStoryContext))]
    partial class MvcStoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("google_sheet_api_service.Models.Story", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("buildingGid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("buildingLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("buildingName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("characterGid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("characterName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("gId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("stroyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Story");
                });
#pragma warning restore 612, 618
        }
    }
}
