// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace google_sheet_api_service.Migrations.MvcDiary
{
    [DbContext(typeof(MvcDiaryContext))]
    partial class MvcDiaryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("google_sheet_api_service.Models.Diary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("characterGid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("characterName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("diaryContentKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("diaryTitleKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("gId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Diary");
                });
#pragma warning restore 612, 618
        }
    }
}
