// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace google_sheet_api_service.Migrations.MvcBuildingStyle
{
    [DbContext(typeof(MvcBuildingStyleContext))]
    partial class MvcBuildingStyleContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("google_sheet_api_service.Models.BuildingStyle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("buildingGid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("buildingName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("buildingStyleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("gId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("imageKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("islandGid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("minLevel")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("BuildingStyle");
                });
#pragma warning restore 612, 618
        }
    }
}
