// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace google_sheet_api_service.Migrations
{
    [DbContext(typeof(MvcBuildingContext))]
    [Migration("20211230091025_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("google_sheet_api_service.Models.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("alreadySettingBuildingLevelCount")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("buildingDescriptionKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("buildingNameKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("gId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("imageKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("islandGid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("islandName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("maxLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Building");
                });
#pragma warning restore 612, 618
        }
    }
}
