// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace google_sheet_api_service.Migrations
{
    [DbContext(typeof(MvcTestFileContext))]
    partial class MvcTestFileContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("google_sheet_api_service.Models.TestFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Test1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Test2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Test3")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Test4")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Test5")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TestFile");
                });
#pragma warning restore 612, 618
        }
    }
}
