// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace google_sheet_api_service.Migrations.MvcSoundSetting
{
    [DbContext(typeof(MvcSoundSettingContext))]
    partial class MvcSoundSettingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("google_sheet_api_service.Models.SoundSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("bellVolume")
                        .HasColumnType("REAL");

                    b.Property<double>("bgmVolume")
                        .HasColumnType("REAL");

                    b.Property<double>("birdVolume")
                        .HasColumnType("REAL");

                    b.Property<int>("islandGid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("islandName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("lakeVolume")
                        .HasColumnType("REAL");

                    b.Property<double>("waveVolume")
                        .HasColumnType("REAL");

                    b.Property<double>("windVolume")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("SoundSetting");
                });
#pragma warning restore 612, 618
        }
    }
}
