// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace google_sheet_api_service.Migrations.MvcBuildingAnimSetting
{
    [DbContext(typeof(MvcBuildingAnimSettingContext))]
    partial class MvcBuildingAnimSettingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("google_sheet_api_service.Models.BuildingAnimSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("buildingSize")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("checkAnimValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("levelUpAnimName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("levelUpAnimValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BuildingAnimSetting");
                });
#pragma warning restore 612, 618
        }
    }
}
